# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0003_auto_20170719_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(default=b'e17eaae5-96f9-48d8-a822-56a656ffedf8', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
